name: Test

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Run test
      run: |
        xcodebuild test -scheme CombineExtensions -destination "platform=iOS Simulator, name=iPhone 11 Pro Max"
